name: Secrets Scan

on:
  push:
    branches: ["**"]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Move .secrets.baseline file
        run: mv .github/.secrets.baseline .

      - name: Scan for secrets
        uses: secret-scanner/action@0.0.2
